### ISSUE TITLE
Implement the ability to specify a preferred state release version

### ISSUE THREAD

**Issue by dkingofpa** [msonnabaum/chef-drush#13]
PEAR's preferred state functionality has been broken for a while and doesn't appear to be on the roadmap to be fixed.  See  [PEAR bug report](https://pear.php.net/bugs/bug.php?id=19138) for more info.

Let's implement some form of that functionality here so we don't have to keep updating the default stable version in the cookbook.  I'll do a pull request soon.

**Comment by dkingofpa** [comment]
See #14 for code.

**Comment by patcon** [comment]
Niiiice. Oh, and hey, the hub pull-request command allows you to convert issues into pull requests, if that's easier :)
