### ISSUE TITLE
Improve usage readme

### ISSUE THREAD

**Issue by rb2k** [msonnabaum/chef-drush#15]
> Simply include the `drush` or `drush::make` recipe wherever you would like drush installed.

You could add an article that this only works if somebody renamed the "chef-drush" folder to just "drush" in case they did a plain git clone

:)

**Comment by patcon** [comment]
Ah yeah, that's a good point -- it's a chef convention (for searchability on github), but totally worth mentioning.

Might be overkill, but could just steal fnichol's template:
https://github.com/fnichol/chef-rvm#-installation

**Comment by patcon** [comment]
Oh wow. Totally forgot about this..! Closing in favour of #28
