### ISSUE TITLE
installing drush 6 via pear fails 

### ISSUE THREAD

**Issue by dergachev** [msonnabaum/chef-drush#16]
Added this to Vagrantfile:

```
:drush => { :version => "devel" }, 
```

Installed OK but running "drush" gets the following message:

```
$ drush
Could not open input file: /usr/bin/drush.php
```

The problem /usr/bin/drush is not a symlink, but expects to be.

This issue was reported on drupal.org:
  http://drupal.org/node/1891660#alter-the-drush-script-so-that-the-drush-pear-install-does-not-need-to-modify-it

Clearly it's an upstream bug, but filing it here for future googlers.

**Comment by mparker17** [comment]
According to the linked issue, this was fixed January 24, 2013.

Recommend we close this.

**Comment by patcon** [comment]
:fireworks:
