### ISSUE TITLE
Drush installation using php_pear, with either devel or beta preferred state causes a logic error

### ISSUE THREAD

**Issue by ksorokin** [msonnabaum/chef-drush#20]
```
php_pear("drush") do
    action [:install]
    retries 0
    retry_delay 2
    cookbook_name :drush
    recipe_name "pear"
    version "devel"
    channel "pear.drush.org"
    package_name "drush"
    preferred_state "stable"
end
```

from other side if you'll specify concrete build version, then you receive 

```
php_pear("drush") do
    action [:install]
    retries 0
    retry_delay 2
    cookbook_name :drush
    recipe_name "pear"
    version "6.0.0"
    channel "pear.drush.org"
    package_name "drush"
    preferred_state "stable"
end
```

So I guess this block should have nested preferred state options for php_pear

```
# Install drush
php_pear "drush" do
    version node['drush']['version']
    channel dc.channel_name
    action :install
end
```

**Comment by mparker17** [comment]
I'm not sure I understand what needs to be done here.

If you include `drush::pear` in your runlist, and set `node['drush']['version'] = '6.0.0'`, it will use PEAR to install a specific version of Drush in the same way you specified in the issue description. For example, in a `Vagrantfile`:

```
config.vm.provision :chef_solo do |chef|
  # ...
  chef.add_recipe "drush::pear"
  # ...
  chef.json = {
    "drush" => {
      "version" => "6.0.0"
    }
  }
end
```

See https://github.com/msonnabaum/chef-drush/blob/master/recipes/pear.rb#L42-L46 for the code that this recipe runs.

**Comment by patcon** [comment]
FWIW, I think this relates to `preferred_state` being broken:
https://github.com/msonnabaum/chef-drush/pull/14#issuecomment-7729573

**Comment by walkah** [comment]
I think this has been resolved?

**Comment by patcon** [comment]
can't say for sure, but i know preferred_state was broken for awhile in php cookbook way back when, and I think lots has changed now. Likely safe to assume this issue is stale for now.

Also, whoop @walkah!
