### ISSUE TITLE
community.opscode.com links to wrong repository

### ISSUE THREAD

**Issue by mparker17** [msonnabaum/chef-drush#21]
http://community.opscode.com/cookbooks/drush links to [msonnabaum/cookbooks](https://github.com/msonnabaum/cookbooks) NOT [this repository](https://github.com/msonnabaum/chef-drush).

**Comment by patcon** [comment]
Can't do this myself. @msonnabaum wanna give me chef community site collab access?

**Comment by msonnabaum** [comment]
Fixed the link and added @patcon as a collaborator.

**Comment by patcon** [comment]
whoopadeedoo
:nail_care:
