### ISSUE TITLE
Allow for patches to be applied via attribute

### ISSUE THREAD

**Issue by patcon** [msonnabaum/chef-drush#6]
This one in particular is what I'll be adding that functionality for dealing with (drush5):
http://drupal.org/node/1109002

Re: http://projects.occupy.net/issues/99

**Comment by msonnabaum** [comment]
I'm very confused on how you propose this be implemented or what the real requirement is here :)

**Comment by patcon** [comment]
haha ok fair enough. Just planning to add an attribute that can be a string or array of links to pull patches from the d.o queues, and will apply them after clone. basically want a way to cherrypick features from dev without going to an unstable release, same as I do with drupal modules

**Comment by msonnabaum** [comment]
Hmm, if there's already a chef way of doing that and maybe precedence in another cookbook that sounds good, but I'm a bit skeptical of that fitting within the scope of a cookbook.

Also, good luck getting any drush5 patches to apply to 4. We made a bunch of api changes early on so it's unlikely that you'll have many that apply. And if they do apply cleanly, let me know if they are marked for backport.

**Comment by patcon** [comment]
No, I get that it's a bit edge-case, so no worries -- I'll just keep my own branch for that. And yeah, that patch is for drush_make, so I would've had to reroll it for drush5, but the actual file change still works a-ok in the make command

**Comment by mparker17** [comment]
Can this be closed?

**Comment by patcon** [comment]
:+1:
